export const EMAIL_MAX_FILES = 20;
export const EMAIL_MAX_FILE_SIZE = 5 * 1024 * 1024;
export const EMAIL_ATTACHMENT_ACCEPT = `
  image/jpeg,image/png,image/gif,image/webp,image/bmp,image/tiff,image/svg+xml,
  application/pdf,
  application/msword,
  application/vnd.openxmlformats-officedocument.wordprocessingml.document,
  application/vnd.ms-excel,
  application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,
  application/vnd.ms-powerpoint,
  application/vnd.openxmlformats-officedocument.presentationml.presentation,
  text/plain,text/csv,
  application/zip,application/x-rar-compressed,application/x-7z-compressed,
  application/vnd.oasis.opendocument.text,
  application/vnd.oasis.opendocument.spreadsheet,
  audio/mpeg,audio/wav,audio/ogg,
  video/mp4,video/x-msvideo,video/quicktime
`;

export const EMAIL_FILES_ALLOWED_EXTENSIONS = [
  "jpg",
  "jpeg",
  "png",
  "gif",
  "webp",
  "bmp",
  "tiff",
  "svg",
  "pdf",
  "doc",
  "docx",
  "xls",
  "xlsx",
  "ppt",
  "pptx",
  "txt",
  "csv",
  "zip",
  "rar",
  "7z",
  "odt",
  "ods",
  "mp3",
  "wav",
  "ogg",
  "mp4",
  "avi",
  "mov",
];
